#ifndef DIAMONDSQUARE_H
#define DIAMONDSQUARE_H

#include "IMG.h"

/**ALGORITIMO DIAMOND-SQUARE (RECEBE A VARIVAL QUEE QUE VAI ARMZENAR AS ALTITUDES,POR REFERENCIA PRA EVITAR COPIAR
, O VALOR MINIMO QUE VAI SER A COR MAIS "BAIXA" E O VALOR MAXIMO QUE VAI SER A COR MAIS ALTA)*/
void diamondSquare(Image &altitudeMap, int minVal, int maxVal);

#endif
